services:

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clothes_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Initialize schema on first run:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  backend:
    image: sbingham0913/clothingpicker-backend:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/clothes_db
      UPLOAD_DIR: /usr/src/app/uploads
    volumes:
      - backend_uploads:/usr/src/app/uploads
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    image: sbingham0913/clothingpicker-frontend:latest
    restart: unless-stopped
    depends_on:
      -  backend
    ports:
      - "80:80"

volumes:
  pgdata:
  backend_uploads:
