services:

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clothes_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Initialize schema on first run:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      COMPOSE_BAKE: true
      # Override .env if needed; docker-compose will inject these
      PORT: 3000
      JWT_SECRET: supersecretkey        # You can override for production later
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/clothes_db
      UPLOAD_DIR: /usr/src/app/uploads
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      # If you want to mount local source for live reload, add:
      # - ./backend/src:/usr/src/app/src
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      -  backend
    ports:
      - "80:80"

volumes:
  pgdata:
